language: node_js
matrix:
 include:
  - node_js: "0.10"
    env: GULP_TASK="test-server"
  - node_js: "4"
    env: GULP_TASK="test-server"
  - node_js: "stable"
    env: GULP_TASK="test-server"
  - node_js: "stable"
    env: GULP_TASK="test-client-travis"
  - node_js: "stable"
    env: GULP_TASK="test-functional"
  - node_js: "stable"
    env: GULP_TASK="test-website"
 fast_finish: true

install: gem install jekyll html-proofer

branches:
  except:
    - /^greenkeeper-.*$/

notifications:
 email: false
